############# English navigation ##############

# main menu
[[main]]
name = "Plateforme fédérale de données scientifiques"
url = "/fr"
weight = 1
identifier = "accueil"

[[main]]
name = "Produit"
url = "/fr/produit"
weight = 2

[[main]]
name = "Survol"
parent = "Produit"
url = "/fr/produit"
weight = 1

[[main]]
name = "Stockage"
parent = "Produit"
url = "/fr/produit/stockage"
weight = 2

[[main]]
name = "Databricks"
parent = "Produit"
url = "/fr/produit/databricks"
weight = 3

[[main]]
name = "Azure App Service"
parent = "Produit"
url = "/fr/produit/app-service"
weight = 5

[[main]]
name = "PostgreSQL"
parent = "Produit"
url = "/fr/produit/postgresql"
weight = 4

[[main]]
name = "Intégrations externes"
parent = "Produit"
url = "/fr/produit/integrations"
weight = 6

[[main]]
name = "Ressources"
url = "/fr/ressources"
weight = 3

[[main]]
name = "Mises à jour"
parent = "Ressources"
url = "https://github.com/ssc-sp/datahub-portal/releases"
weight = 2

[[main]]
name = "Communauté GCéchange"
parent = "Ressources"
url = "https://gcxgce.sharepoint.com/teams/10002160/SitePages/fr/Home.aspx"
weight = 4

[[main]]
name = "À propos"
url = "/fr/a-propos"
weight = 4

[[main]]
name = "Survol"
parent = "À propos"
url = "/fr/a-propos"
weight = 1

[[main]]
name = "Plan d'innovation"
parent = "À propos"
url = "/fr/a-propos/plan"
weight = 2

[[main]]
name = "Conditions générales"
parent = "À propos"
url = "/fr/a-propos/conditions-generales"
weight = 4

[[main]]
name = "Confidentialité"
parent = "À propos"
url = "/fr/a-propos/confidentialite"
weight = 5

[[main]]
name = "Securité"
parent = "À propos"
url = "/fr/a-propos/securite"
weight = 6

[[main]]
name = "Contactez-nous"
parent = "À propos"
url = "/fr/contact"
weight = 7

[[main]]
name = "Se connecter"
url = "https://datahub-scientifique-federal.canada.ca/"
weight = 16
