############# English navigation ##############

# main menu
[[main]]
name = "Plateforme fédérale de données scientifiques"
url = "/fr"
weight = 1
identifier = "acceuil"

[[main]]
name = "Plate-forme"
url = "/fr/platform"
weight = 5

[[main]]
name = "Proposition"
parent = "Plate-forme"
url = "/fr/proposition"
weight = 1

[[main]]
name = "Composants"
parent = "Plate-forme"
url = "/fr/components"
weight = 5

[[main]]
name = "Communauté"
url = "/fr/communaute"
weight = 10

[[main]]
name = "Participez"
url = "/fr/impliquez-vous"
parent = "Communauté"
weight = 1

[[main]]
name = "Règles d'engagement"
parent = "Communauté"
url = "/fr/regles-dengagement"
weight = 1

[[main]]
name = "Contactez-nous"
url = "/fr/contact"
weight = 15
