---
name: Lint

on:
  push: {}
  pull_request: {}
  workflow_dispatch:

permissions: read-all

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0

      - name: Restore super-linter cache
        uses: actions/cache@v3
        with:
          path: /tmp/super_linter_image.tar
          key: ${{ runner.os }}-super-linter-${{ hashFiles('docker-image-version.txt') }}
      
      - name: Load super-linter image from cache
        run: |
          if [ -f /tmp/super_linter_image.tar ]; then
            docker load -i /tmp/super_linter_image.tar
          fi

      - name: Run Super-linter
        uses: super-linter/super-linter@v7.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_CHECKOV: false
          VALIDATE_JSCPD: false
          VALIDATE_JSON_PRETTIER: false
          VALIDATE_YAML_PRETTIER: false
          SUPPRESS_POSSUM: true

      - name: Save super-linter image to cache
        run: docker save super-linter/super-linter:7.1.0 -o /tmp/super_linter_image.tar
